Repository pyinstaller/pyinstaller, pull requests merged in 2019-06, with the labels that each got.

#4037 Correct spelling of NSPrincipalClass in Spec File docs
  doc/spec-files.rst
Labels: documentation

#2951 doc: update runtime information
  doc/runtime-information.rst
Labels: documentation

#4105 Hooks: Add hook for ttkthemes
  PyInstaller/hooks/hook-ttkthemes.py
  news/4105.hooks.rst
Labels: hooks

#4120 Add pywt hook
  PyInstaller/hooks/hook-pywt.py
  news/4120.hooks.rst
Labels: hooks, needs more work

#4119 Tests: Test data should get consistent line ending regardless of host
  .gitattributes
Labels: pr:commit-message, test-suite

#4250 Hooks: Create hook-migrate.py.
  PyInstaller/hooks/hook-migrate.py
  news/4250.hooks.rst
Labels: needs more work, pr:changelog-entry

#4109 Add a hook for Radicale
  PyInstaller/hooks/hook-radicale.py
  news/4109.hooks.rst
Labels: hooks

#4270 Make notebook hook more robust to whether directories actually exist
  PyInstaller/hooks/hook-notebook.py
  news/4270.hooks.rst
Labels: pr:changelog-entry
