Repository pyinstaller/pyinstaller, pull requests merged in 2020-04, with the labels that each got.

#4769 Cleanup: Fix typo in __init__.py
  PyInstaller/__init__.py
Labels: @low / cleanup, ready to merge

#4760 Hooks: Add webassets hook.
  PyInstaller/hooks/hook-webassets.py
  news/4760.hooks.rst
Labels: ready to merge

#3900 fix unable to find "C:\Users\user\nltk_data" #3799
  PyInstaller/hooks/hook-nltk.py
  news/3900.hooks.rst
Labels: ready to merge

#4788 Git/Config: Add environment folder ignores
  .gitignore
Labels: area:project infrastructure, ready to merge

#4786 Monthly dependency update
  tests/requirements-libraries.txt
Labels: area:tests/ci, area:tests/ci/pyup

#4632 Issue pyinstaller#4576: Add hook for jaraco.text
  PyInstaller/hooks/hook-jaraco.text.py
  news/4576.hooks.rst
  news/4632.hooks.rst
Labels: area:hooks, state:needs more work

#4634 Hook LightGBM
  PyInstaller/hooks/hook-lightgbm.py
  news/4634.hooks.rst
Labels: area:hooks
