Repository pyinstaller/pyinstaller, pull requests merged in 2020-10, with the labels that each got.

#5175 hooks: tkinter: collect Tcl modules directory
  PyInstaller/hooks/hook-_tkinter.py
  news/5175.hooks.rst
Labels: ready to merge

#5132 depends: Exclude more unix/Linux graphical interface libraries
  PyInstaller/depend/dylib.py
Labels: DO NOT MERGE

#5259 Build: OSX: Fixed the ineffectiveness of the --distpath argument for t…
  PyInstaller/building/osx.py
  news/4892.build.rst
Labels: bugfix, platform:OS X

#5274 Bootloader: (OSX) Bump MACOSX_DEPLOYMENT_TARGET from 10.7 to 10.13.
  README.rst
  bootloader/wscript
  news/4627.bootloader.rst
  news/4886.bootloader.rst
Labels: area:bootloader, platform:OS X

#5006 Fix matplotlib hook to support matplotlib 3.3.0
  PyInstaller/hooks/hook-matplotlib.py
  PyInstaller/hooks/rthooks.dat
  PyInstaller/hooks/rthooks/pyi_rth_mpldata.py
  news/5006.hooks.rst
  tests/functional/test_hooks/test_matplotlib.py
Labels: @high, bugfix, state:needs more work

#5276 OSX: Add capability for already-running apps to accept URL & drag'n drop events via Apple Event forwarding
  bootloader/src/pyi_utils.c
  news/5276.bootloader.rst
  tests/functional/scripts/pyi_pyqt5_log_events.py
  tests/functional/specs/pyi_osx_event_forwarding.spec
  tests/functional/test_apple_events.py
Labels: area:bootloader, platform:OS X

#5291 tests: replace skipif_xxx for platform-specific tests by markers
  PyInstaller/utils/conftest.py
  PyInstaller/utils/tests.py
  news/1427.tests.rst
  setup.cfg
  tests/functional/test_apple_events.py
  tests/functional/test_basic.py
  tests/functional/test_import.py
  tests/functional/test_libraries.py
  tests/functional/test_path_encodings.py
  tests/functional/test_signals.py
  tests/functional/test_updating_manifest.py
  tests/unit/test_TOC.py
  tests/unit/test_depend_utils.py
  tests/unit/test_modulegraph_more.py
Labels: @low / cleanup, area:test-suite
