Repository pyinstaller/pyinstaller, pull requests merged in 2021-04, with the labels that each got.

#5702 tests: skip test_unbuffered_stdio on CI
  tests/functional/test_unbuffered_stdio.py
Labels: merge-on-ci-pass

#5700 ci: consolidate with github actions
  .github/workflows/cancel.yml
  .github/workflows/ci.yml
  .github/workflows/macos.yml
  .travis.yml
  appveyor.yml
Labels: DO NOT MERGE

#5698 reduce modulegraph stack depth and implement 'yield from'
  .gitignore
  PyInstaller/lib/modulegraph/modulegraph.py
  PyInstaller/lib/modulegraph/util.py
  news/5698.bugfix.rst
  tests/unit/test_modulegraph/test_modulegraph.py
Labels: squash-merge-on-ci-pass

#5740 Analysis: ctypes: Guard against errors triggered by find_library(). (#5734)
  PyInstaller/depend/utils.py
  news/5734.bugfix.rst
  tests/functional/test_regression.py
Labels: merge-on-ci-pass

#5750 compat: fix python library lookup for recent versions of RHSCL python
  PyInstaller/compat.py
  news/5749.bugfix.rst
Labels: merge-on-ci-pass

#5763 bootloader: obfuscate the CArchive MAGIC pattern stored in executable
  bootloader/src/pyi_archive.c
  news/5762.bugfix.rst
Labels: merge-on-ci-pass

#5765 compat: implement timeouts on subprocess
  PyInstaller/compat.py
Labels: merge-on-ci-pass

#5770 depend: expand _win_includes list with additiona DLLs from vcredist
  PyInstaller/depend/dylib.py
  news/5770.bugfix.rst
Labels: merge-on-ci-pass

#5778 depend: add vcomp140.dll to _win_includes list
  PyInstaller/depend/dylib.py
Labels: merge-on-ci-pass

#5774 Hook-utils: copy_metadata(): Preserve metadata folder name.
  PyInstaller/hooks/hook-gevent.py
  PyInstaller/utils/hooks/__init__.py
  doc/hooks.rst
  news/5774.bugfix.rst
  tests/unit/test_hookutils.py
Labels: squash-merge-on-ci-pass
