Repository pyinstaller/pyinstaller, pull requests merged in 2021-09, with the labels that each got.

#6180 hooks: add hook for pandas.plotting
  PyInstaller/hooks/hook-pandas.plotting.py
  news/5994.hooks.rst
  tests/functional/test_libraries.py
Labels: needs backport

#6182 hookutils: qt: fix library handling for Anaconda-installed Qt on macOS
  PyInstaller/utils/hooks/qt.py
  news/6181.hooks.rst
Labels: needs backport

#6184 ci: enable workflows on v4 branch
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/validate-new-news.yml
Labels: needs backport

#6188 macOS: robustify macOS assembly pipeline
  PyInstaller/building/utils.py
  PyInstaller/utils/osx.py
  news/6167.bugfix.rst
Labels: needs backport

#6195 Implement support for importlib.resources
  PyInstaller/loader/pyimod03_importers.py
  news/5616.feature.rst
  tests/functional/scripts/pyi_importlib_resources.py
  tests/functional/test_importlib_resources.py
  tests/requirements-libraries.txt
Labels: needs backport

#6201 depend: suppress warnings about missing api-ms-win-core-* DLLs
  PyInstaller/depend/dylib.py
  news/6201.bugfix.rst
Labels: needs backport

#6197 Do not throw an exception if the DISTPATH and workpath exist
  PyInstaller/building/build_main.py
Labels: merge-on-ci-pass, needs backport

#6218 bootloader: Fix searching for 'strip'
  bootloader/wscript
Labels: needs backport

#6242 loader: fix FrozenImporter.get_source for packages' __init__.py files
  PyInstaller/loader/pyimod03_importers.py
  news/6237.bugfix.rst
Labels: needs backport

#6243 building: Windows: embed manifest into onedir executable by default
  PyInstaller/building/api.py
  PyInstaller/building/makespec.py
  news/6223.breaking.rst
  news/6223.feature.rst
Labels: merge-on-ci-pass

#6250 hooks: qt5: add hooks for QtPositioning and QtLocation modules
  PyInstaller/hooks/hook-PyQt5.QtLocation.py
  PyInstaller/hooks/hook-PyQt5.QtPositioning.py
  PyInstaller/hooks/hook-PySide2.QtLocation.py
  PyInstaller/hooks/hook-PySide2.QtPositioning.py
  news/6250.hooks.rst
Labels: needs backport

#6252 building: reorganize the EXE assembly function
  PyInstaller/building/api.py
  news/6251.bugfix.rst
Labels: needs backport

#6254 building: makespec: do not hard-code spec file's directory as pathex
  PyInstaller/building/makespec.py
  news/6254.bugfix.rst
Labels: needs backport
