Repository pyinstaller/pyinstaller, pull requests merged in 2022-04, with the labels that each got.

#6735 Remove timeout on UPX subprocesses (#6722).
  PyInstaller/building/utils.py
  news/6722.bugfix.rst
Labels: needs backport

#6744 bootloader: remove superfluous argument to pyi_arch_status_new() call
  bootloader/src/pyi_main.c
  news/6742.bootloader.rst
Labels: needs backport

#6749 Assorted documentation updates
  COPYING.txt
  PyInstaller/utils/hooks/__init__.py
  doc/CHANGES.rst
  doc/_common_definitions.txt
  doc/_extensions/pyi_sphinx_roles.py
  doc/_static/css/pyinstaller.css
  doc/advanced-topics.rst
  doc/bootloader-building.rst
  doc/conf.py
  doc/contributing.rst
  doc/development/branch-model.rst
  doc/development/coding-conventions.rst
  doc/development/commit-messages.rst
  doc/development/documentation.rst
  doc/development/pull-requests.rst
  doc/development/testing.rst
  doc/feature-notes.rst
  doc/hooks-config.rst
  doc/hooks.rst
  doc/index.rst
  doc/installation.rst
  doc/license.rst
  doc/man/pyi-makespec.rst
  doc/operating-mode.rst
  doc/requirements.rst
  doc/requirements.txt
  doc/runtime-information.rst
  doc/spec-files.rst
  doc/usage.rst
  doc/when-things-go-wrong.rst
Labels: Version 5

#6789 Bugfix/prevent site collection (closes #6785)
  PyInstaller/utils/hooks/__init__.py
  news/6789.bugfix.rst
Labels: merge-on-ci-pass
